### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by pmfx**

### CODE REVIEW

**Comment by pmfx** [comment]
I will add more commits to this PR later.

**Comment by Pathologic** [comment]
Thank you. Probably it need lexicons, I'll add them later :cat:

**Comment by pmfx** [comment]
New style:

Empty:
obraz

Progress:
obraz

Uploaded:
obraz

I will try to add compatibility with EVO "darkness" mode next.

**Comment by pmfx** [comment]
Style for EVO darkness mode

obraz

**Comment by pmfx** [comment]
@Pathologic OK, I think it is ready. Can you test and merge?

**Pull request merged**
